apiVersion: 1

contactPoints:
  - orgId: 1
    name: warroom-thesmartai-email
    receivers:
      - uid: warroom-thesmartai-email
        type: email
        settings:
          addresses: yeatsluo@gmail.com
          singleEmail: false
        disableResolveMessage: false
